# Generated by Django 3.1.5 on 2021-07-27 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210726_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold',
            name='client_email',
            field=models.CharField(default='', max_length=300),
        ),
    ]
