# Generated by Django 3.1.5 on 2021-07-27 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_sold_client_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sold',
        ),
    ]
