# Generated by Django 3.1.5 on 2021-07-27 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_delete_sold'),
    ]

    operations = [
        migrations.CreateModel(
            name='sold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product', models.CharField(default='', max_length=100)),
                ('name', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('variant', models.CharField(default='', max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('client_email', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
