# Generated by Django 3.1.5 on 2021-07-27 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_sold'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sold',
        ),
    ]
