# Generated by Django 3.1.5 on 2021-07-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sold',
            name='order_date',
            field=models.DateField(auto_now=True),
        ),
    ]
