# Generated by Django 3.1.5 on 2021-07-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20210729_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold',
            name='client_id',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='sold',
            name='client_email',
            field=models.CharField(max_length=300),
        ),
    ]
