# Generated by Django 3.2.6 on 2021-08-31 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20210729_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold',
            name='order_status',
            field=models.CharField(choices=[('BUYING', 'Not paid yet'), ('PAID', 'Paid but not shipped'), ('SHIPPED', 'Order has been shipped'), ('ARRIVED', 'Order has arrive on the warehouse')], default='PAID', max_length=7),
        ),
        migrations.AddField(
            model_name='sold',
            name='second_shipped',
            field=models.CharField(choices=[('NOT SHIPPED', 'Not shipped yet'), ('SHIPPED', 'Shipped')], default='NOT SHIPPED', max_length=11),
        ),
    ]
