# Generated by Django 3.2.6 on 2021-08-31 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20210831_0210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sold',
            old_name='second_shipped',
            new_name='shipped_to_client',
        ),
    ]
