# Generated by Django 3.2.6 on 2021-08-31 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_rename_second_shipped_sold_shipped_to_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_view',
            name='shipping',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
