# Generated by Django 3.2.6 on 2021-09-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_product_view_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold',
            name='bill_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='sold',
            name='order_status',
            field=models.CharField(choices=[('BUYING', 'Not paid yet'), ('PAID', 'Paid but not shipped'), ('SHIPPED', 'Order has been shipped'), ('ARRIVED', 'Order has arrive on the warehouse')], default='BUYING', max_length=7),
        ),
    ]
