# Generated by Django 3.2.6 on 2021-09-02 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20210901_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold',
            name='rmprice',
            field=models.FloatField(default=1000),
            preserve_default=False,
        ),
    ]
