# Generated by Django 3.2.6 on 2021-09-02 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_sold_rmprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sold',
            name='order_status',
            field=models.CharField(choices=[('NOT PAID', "The client hasn't pay the bill yet"), ('BUYING', 'Bill has been paid, waiting to order the product'), ('ORDERED', 'The product has been ordered'), ('SHIPPED', 'Order has been shipped'), ('ARRIVED', 'Order has arrive on the warehouse')], default='NOT PAID', max_length=8),
        ),
        migrations.AlterField(
            model_name='sold',
            name='shipped_to_client',
            field=models.CharField(choices=[('NOT SHIPPED', 'Order is on the warehouse'), ('SHIPPED', 'Order has been shipped out')], default='NOT SHIPPED', max_length=11),
        ),
    ]
