# Generated by Django 3.2.6 on 2021-09-02 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20210902_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sold',
            name='shipped_to_client',
            field=models.CharField(choices=[("HAVEN'T ARRIVED", 'Waiting for the order to arrive'), ('NOT SHIPPED', 'Order is on the warehouse'), ('SHIPPED', 'Order has been shipped out')], default='NOT SHIPPED', max_length=15),
        ),
    ]
