# Generated by Django 3.2.6 on 2021-09-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_sold_shipped_to_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold',
            name='markup',
            field=models.FloatField(default=10),
        ),
    ]
