# Generated by Django 3.2.6 on 2021-09-09 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_sold_markup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sold',
            name='markup',
        ),
        migrations.AddField(
            model_name='sold',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
