# Generated by Django 3.2.6 on 2021-09-10 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20210909_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='calc_conf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markup', models.FloatField()),
                ('singapore_rate', models.FloatField()),
                ('singapore_sensitive_rate', models.FloatField()),
                ('brunel_rate', models.FloatField()),
                ('brunel_sensitive_rate', models.FloatField()),
                ('malaysia1_rate', models.FloatField()),
                ('malaysia1_sensitive_rate', models.FloatField()),
                ('malaysia2_rate', models.FloatField()),
                ('malaysia2_sensitive_rate', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='sold',
            name='id',
        ),
        migrations.AlterField(
            model_name='sold',
            name='id_product',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
