# Generated by Django 3.2.6 on 2021-09-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20210910_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold',
            name='id',
            field=models.AutoField(auto_created=True, default=10, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sold',
            name='id_product',
            field=models.CharField(max_length=100),
        ),
    ]
