# Generated by Django 3.2.6 on 2021-09-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20210910_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sold',
            name='id_product',
            field=models.CharField(default='', max_length=100),
        ),
    ]
