# Generated by Django 3.2.6 on 2021-09-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_alter_sold_id_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='calc_conf',
            name='air_number',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calc_conf',
            name='convert_rate',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calc_conf',
            name='sea_1_min',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calc_conf',
            name='sea_1_number',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calc_conf',
            name='sea_1_price_over_min',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calc_conf',
            name='sea_1_price_under_min',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calc_conf',
            name='sea_2_min',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calc_conf',
            name='sea_2_number',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calc_conf',
            name='sea_2_price_over_min',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calc_conf',
            name='sea_2_price_under_min',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
