# Generated by Django 3.2.6 on 2021-09-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_auto_20210910_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold',
            name='bill_new',
            field=models.BooleanField(default=False),
        ),
    ]
