# Generated by Django 3.2.6 on 2021-09-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_sold_bill_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sold',
            name='length',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sold',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sold',
            name='width',
            field=models.FloatField(default=0),
        ),
    ]
