# Generated by Django 3.2.6 on 2021-09-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_auto_20210912_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold',
            name='shipping_price',
            field=models.FloatField(default=0),
        ),
    ]
