# Generated by Django 3.2.6 on 2021-09-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_auto_20210912_0456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sold',
            old_name='shipping_price',
            new_name='air_price',
        ),
        migrations.AddField(
            model_name='sold',
            name='sea_1_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sold',
            name='sea_2_price',
            field=models.FloatField(default=0),
        ),
    ]
