# Generated by Django 3.2.6 on 2021-09-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_auto_20210912_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold',
            name='shipping_choose',
            field=models.CharField(choices=[('', ''), ('Air', 'Air'), ('Sea 1', 'Sea 1'), ('Sea 2', 'Sea 2')], default='', max_length=5),
        ),
    ]
