# Generated by Django 3.2.6 on 2021-09-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_sold_shipping_choose'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold',
            name='air_bill',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sold',
            name='sea_1_bill',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sold',
            name='sea_2_bill',
            field=models.CharField(default='', max_length=20),
        ),
    ]
