# Generated by Django 3.2.6 on 2021-09-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_auto_20210913_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold',
            name='shipping_status',
            field=models.CharField(choices=[('NOT PAID', "The client hasn't pay the bill yet"), ('NOT SHIPPED', 'Bill has been paid, waiting to ship the product'), ('SHIPPED', 'Order has been shipped'), ('ARRIVED', 'Order has arrive on the warehouse')], default='NOT PAID', max_length=11),
        ),
    ]
