# Generated by Django 3.2.6 on 2021-09-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_sold_shipping_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='soldMain',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.sold',),
        ),
        migrations.RemoveField(
            model_name='sold',
            name='air_bill',
        ),
        migrations.RemoveField(
            model_name='sold',
            name='sea_1_bill',
        ),
        migrations.RemoveField(
            model_name='sold',
            name='sea_2_bill',
        ),
        migrations.AddField(
            model_name='sold',
            name='shipping_bill',
            field=models.FloatField(default=0),
        ),
    ]
