# Generated by Django 3.2.6 on 2021-09-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_auto_20210914_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sold',
            name='shipping_bill',
            field=models.CharField(default='', max_length=20),
        ),
    ]
